
/*
 * Editor client script for DB table homily
 * Automatically generated by http://editor.datatables.net/generator
 */

(function($){

$(document).ready(function() {
	var editor = new $.fn.dataTable.Editor( {
		"ajax": "php/table.homily.php",
		"table": "#homily",
		"fields": [
			{
				"label": "Date",
				"name": "date",
				"type": "date",
				"dateFormat": "mm\/dd\/y",
				"dateImage": "images\/calender.png"
			},
			{
				"label": "Title",
				"name": "title",
				"type": "text"
			},
			{
				"label": "Gospel",
				"name": "gospel",
				"type": "select",
				"ipOpts": [
					{
						"label": "Mark",
						"value": "Mark"
					},
					{
						"label": "Mathew",
						"value": "Mathew"
					},
					{
						"label": "Luke",
						"value": "Luke"
					},
					{
						"label": "John",
						"value": "John"
					}
				]
			},
			{
				"label": "Calendar Year",
				"name": "calendarYear",
				"type": "select",
				"ipOpts": [
					{
						"label": "A",
						"value": "A"
					},
					{
						"label": "B",
						"value": "B"
					},
					{
						"label": "C",
						"value": "C"
					}
				]
			},
			{
				"label": "Homily",
				"name": "homily",
				"type": "textarea"
			}
		]
	} );

	$('#homily').dataTable( {
		"dom": "Tfrtip",
		"ajax": "php/table.homily.php",
		"columns": [
			{
				"data": "date"
			},
			{
				"data": "title"
			},
			{
				"data": "gospel"
			},
			{
				"data": "calendarYear"
			},
			{
				"data": "homily"
			}
		],
		"tableTools": {
			"sRowSelect": "os",
			"aButtons": [
				{ "sExtends": "editor_create", "editor": editor },
				{ "sExtends": "editor_edit",   "editor": editor },
				{ "sExtends": "editor_remove", "editor": editor }
			]
		}
	} );
} );

}(jQuery));

