<?php if (!defined('DATATABLES')) exit(); // Ensure being used in DataTables env.

/*
 * DB connection script for Editor
 * Automatically generated by http://editor.datatables.net/generator
 */
$tz = ini_get(date.timezone);
if (empty($tz)) date_default_timezone_set('America/New_York');
define ('NOW', date('Y-m-d H:i:s'));
// Enable error reporting for debugging (remove for production)
error_reporting(E_ALL);
ini_set('display_errors', '1');



/*
 * Edit the following with your database connection options
 */
$sql_details = array(
	"type" => "Mysql",
	"user" => "dad",
	"pass" => "hodie8888",
	"host" => "localhost",
	"port" => "",
	"db"   => "deacon",
	"dsn"  => "charset=utf8"
);

