
-- 
-- Editor server script for DB table homily
-- Automatically generated by http://editor.datatables.net/generator
-- 

CREATE TABLE `homily` (
	`id` int(10) NOT NULL auto_increment,
	`date` timestamp,
	`title` varchar(255) default NULL,
	`gospel` varchar(255) default NULL,
	`calendarYear` varchar(255) default NULL,
	`homily` text default NULL,
	PRIMARY KEY  (`id`)
);

